var film1 = [ 'Mord ist ihr Hobby <hr>01.1/1',
'Mord ist ihr Hobby <hr>01.1/2',
'Mord ist ihr Hobby <hr>01.1/3',
'Mord ist ihr Hobby <hr>01.2/1',
'Mord ist ihr Hobby <hr>01.2/2',
'Mord ist ihr Hobby <hr>01.2/3',
'Mord ist ihr Hobby <hr>02.1/1',
'Mord ist ihr Hobby <hr>02.1/2',
'Mord ist ihr Hobby <hr>02.1/3',
'Mord ist ihr Hobby <hr>02.2/1',
'Mord ist ihr Hobby <hr>02.2/2',
'Mord ist ihr Hobby <hr>02.2/3',
'Mord ist ihr Hobby <hr>03.1/1',
'Mord ist ihr Hobby <hr>03.1/2',
'Mord ist ihr Hobby <hr>03.1/3',
'Mord ist ihr Hobby <hr>03.2/1',
'Mord ist ihr Hobby <hr>03.2/2',
'Mord ist ihr Hobby <hr>03.2/3',
'Mord ist ihr Hobby <hr>04.1/1',
'Mord ist ihr Hobby <hr>04.1/2',
'Mord ist ihr Hobby <hr>04.1/3',
'Mord ist ihr Hobby <hr>04.2/1',
'Mord ist ihr Hobby <hr>04.2/2',
'Mord ist ihr Hobby <hr>04.2/3',
'Mord ist ihr Hobby <hr>05.1/1',
'Mord ist ihr Hobby <hr>05.1/2',
'Mord ist ihr Hobby <hr>05.1/3',
'Mord ist ihr Hobby <hr>05.2/1',
'Mord ist ihr Hobby <hr>05.2/2',
'Mord ist ihr Hobby <hr>05.2/3',
'Mord ist ihr Hobby <hr>06.1/1',
'Mord ist ihr Hobby <hr>06.1/2',
'Mord ist ihr Hobby <hr>06.1/3',
'Mord ist ihr Hobby <hr>06.2/1',
'Mord ist ihr Hobby <hr>06.2/2',
'Mord ist ihr Hobby <hr>06.2/3',
'Mord ist ihr Hobby <hr>07.1/1',
'Mord ist ihr Hobby <hr>07.1/2',
'Mord ist ihr Hobby <hr>07.1/3',
'Mord ist ihr Hobby <hr>07.2/1',
'Mord ist ihr Hobby <hr>07.2/2',
'Mord ist ihr Hobby <hr>07.2/3',
'Mord ist ihr Hobby <hr>08.1/1',
'Mord ist ihr Hobby <hr>08.1/2',
'Mord ist ihr Hobby <hr>08.1/3',
'Mord ist ihr Hobby <hr>08.2/1',
'Mord ist ihr Hobby <hr>08.2/2',
'Mord ist ihr Hobby <hr>08.2/3',
'Mord ist ihr Hobby <hr>09.1/1',
'Mord ist ihr Hobby <hr>09.1/2',
'Mord ist ihr Hobby <hr>09.1/3',
'Mord ist ihr Hobby <hr>09.2/1',
'Mord ist ihr Hobby <hr>09.2/2',
'Mord ist ihr Hobby <hr>09.2/3',
'Mord ist ihr Hobby <hr>10.1/1',
'Mord ist ihr Hobby <hr>10.1/2',
'Mord ist ihr Hobby <hr>10.1/3',
'Mord ist ihr Hobby <hr>10.2/1',
'Mord ist ihr Hobby <hr>10.2/2',
'Mord ist ihr Hobby <hr>10.2/3',
'Mord ist ihr Hobby <hr>11.1/1',
'Mord ist ihr Hobby <hr>11.1/2',
'Mord ist ihr Hobby <hr>11.1/3',
'Mord ist ihr Hobby <hr>11.2/1',
'Mord ist ihr Hobby <hr>11.2/2',
'Mord ist ihr Hobby <hr>11.2/3',
'Mord ist ihr Hobby <hr>12.1/1',
'Mord ist ihr Hobby <hr>12.1/2',
'Mord ist ihr Hobby <hr>12.1/3',
'Mord ist ihr Hobby <hr>12.2/1',
'Mord ist ihr Hobby <hr>12.2/2',
'Mord ist ihr Hobby <hr>12.2/3',
'Miss Marple - 16 Uhr 50 ab Paddington <hr>M. Rutherford',
'Miss Marple - Mörder Ahoi <hr>M. Rutherford',
'Miss Marple - Der Wachsblumenstrauß <hr>M. Rutherford',
'Miss Marple - Vier Frauen und ein Mord <hr>M. Rutherford',
'Miss Marple - Die Tote in der Bibliothek <hr>J. Hickson (BBC)',
'Miss Marple - Die Schattenhand <hr>J. Hickson (BBC)',
'Miss Marple - Ein Mord wird angekündigt <hr>J. Hickson (BBC)',
'Miss Marple - Das Geheimnis der Goldmine <hr>J. Hickson (BBC)',
'Miss Marple - Mord im Pfarrhaus <hr>J. Hickson (BBC)',
'Miss Marple - Ruhe unsanft <hr>J. Hickson (BBC)',
'Miss Marple - Das Schicksal in Person <hr>J. Hickson (BBC)',
'Miss Marple - Bertrams Hotel <hr>J. Hickson (BBC)',
'Miss Marple - 16 Uhr 50 ab Paddington <hr>J. Hickson (BBC)',
'Miss Marple - Karibische Affäre <hr>J. Hickson (BBC)',
'Miss Marple - They do it with mirrors <hr>J. Hickson (BBC)',
'Miss Marple - The mirror crack&apos;d from side to side <hr>J. Hickson (BBC)',
'Mord im Orientexpress <hr>2017',
'Dr. Dolittle 1 ',
'Dr. Dolittle 2 ',
'Dr. Dolittle 3 ',
'Lissi und der wilde Kaiser ',
'Traumschiff Surprise - Periode 1 ',
'Der Schuh des Manitu ',
'Hui Buh, das Schlossgespenst ',
'Wickie und die starken Männer <hr>Bully',
'Kevin allein zu Haus ',
'Ein Schweinchen namens Babe ',
'Deine, meine & unsere ',]
var film2 = [ 'Der rosarote Panther 1 ',
'Der rosarote Panther 2 ',
'Monsieur Claude und seine Töchter ',
'Kein Pardon ',
'Willkommen bei den Sch&apos;tis ',
'1 1/2 Ritter auf der Suche nach der hinreißenden Herzelinde ',
'7 Zwerge - Männer allein im Wald ',
'Ostfriesisch für Anfänger ',
'Fack ju Göhte ',
'Das Pubertier ',
'Vatertage - Opa über Nacht ',
'Er ist wieder da ',
'Horst Schlämmer - Isch kandidiere! ',
'Mein Name ist Nobody ',
'Robinson Jr. ',
'Peter Pan <hr>Disney',
'Die Eiskönigin - Völlig unverfroren ',
'Die Eiskönigin - Version zum Mitsingen ',
'Die Eiskönigin - Olaf taut auf <hr>mit Kurzfilm "Partyfieber"',
'Rapunzel neu verföhnt ',
'Alice im Wunderland <hr>Disney Zeichentrick',
'Alice im Wunderland <hr>Disney Spielfilm',
'Ratatouille ',
'Merida ',
'Mary Poppins <hr>Disc 1 mit Hauptfilm',
'Mary Poppins <hr>Disc 2 mit Extras',
'Mary Poppins&apos; Rückkehr ',
'Die Schöne und das Biest <hr>Disney Zeichentrick',
'Maleficent, die dunkle Fee ',
'Cinderella <hr>Disney Spielfilm',
'Saving Mr. Banks ',
'Christopher Robin <hr>Disney Spielfilm',
'Meisterschaft im Seitensprung <hr>Doris Day (Don&apos;t eat the Daisies)',
'Caprice <hr>Doris Day / falsch bedruckt mit "Eine zuviel im Bett"',
'Eine zuviel im Bett <hr>Doris Day / falsch bedruckt mit "Caprice"',
'Bitte nicht stören <hr>Doris Day (Umzug nach England)',
'Schick mir keine Blumen <hr>Doris Day (Hypochondrie)',
'Bettgeflüster <hr>Doris Day (Ex-Rex)',
'Ein Pyjama für zwei <hr>Doris Day (VIP)',
'Dinner for One ',
'Ödipussi <hr>Loriot',
'Pappa ante portas <hr>Loriot',
'Herricht & Preil - Die besten Sketche ',
'Der Baulöwe <hr>R. Herricht',
'Bean - Der ultimative Katastrophenfilm ',
'Ferienspaß mit Mr. Bean ',
'Brust oder Keule <hr>Louis de Funès',
'Onkel Paul, die große Pflaume <hr>Louis de Funès',
'Balduin, das Nachtgespenst <hr>Louis de Funès',
'Die große Sause <hr>Louis de Funès',
'Peanuts - Der Film ',
'Operation: Nussknacker ',
'Pippi <hr>langer Zeichentrickfilm',
'Pippi außer Rand und Band <hr>Spielfilm mit Inger Nilsson',
'Hier kommt Lola ',
'Mister Twister ',
'Pittiplatsch im Koboldland <hr>Teil 4 / DVD 1',
'Pittiplatsch im Koboldland <hr>Teil 4 / DVD 2',
'Unser Sandmännchen <hr>7 spannende Episoden mit Hrn. Fuchs & Fr. Elster',
'Geschichten aus dem Märchenwald <hr>Teil 1',
'Geschichten aus dem Märchenwald <hr>Teil 2',
'Geschichten aus dem Märchenwald <hr>Teil 3',
'Geschichten aus dem Märchenwald <hr>Teil 4',
'Heidi <hr>Spielfilm 2015',
'Bibi Blocksberg <hr>Spielfilm',
'Bibi Blocksberg und das Geheimnis der blauen Eulen ',
'Pünktchen und Anton <hr>"das Original"',
'Pünktchen und Anton <hr>2010',
'Kampf der Kobolde <hr>Disc 1',
'Kampf der Kobolde <hr>Disc 2',
'Eine zauberhafte Nanny ',
'Eine zauberhafte Nanny - ... neues Abenteuer ',
'Die wilden Hühner ',
'Justin - Völlig verrittert ',
'Herr Figo [1] und das Geheimnis der Perlenfabrik ',
'Herr Figo [2] auf der Suche nach dem verlorenen Zahn ',
'Tim und Struppi <hr>Das Geheimnis der Einhorn',
'Der kleine Prinz <hr>Zeichentrick',
'Dinosaurier <hr>Disney',
'Konferenz der Tiere ',
'Mein Freund der Delfin ',
'Felix - Ein Hase auf Weltreise ',
'Lars, der kleine Eisbär ',
'Michel in der Suppenschüssel <hr>Spielfilm',
'Happy Feet ',
'Horton hört ein Hu! ',
'Wickie und die starken Männer <hr>2 Zeichentrick-Folgen',
'Belle und Sebastian ',
'Free Willy [1] Ruf der Freiheit ',
'Free Willy [2] Rettung aus der Piratenbucht ',
'Rocca verändert die Welt ',
'Kedi - Von Katzen und Menschen ',
'Schweinchen Wilbur und seine Freunde <hr>"Charlotte&apos;s Web"',
'Spiderwicks ',
'Das Hundehotel ',
'Hook ',
'Die Schneekönigin [1] <hr>Zeichentrick',
'Die Schneekönigin [2] <hr>Zeichentrick',
'Robinson Crusoe <hr>Zeichentrick',
'Mein Freund, der Wasserdrache ',]
var film3 = [ 'Die Schöne und das Biest <hr>Spielfilm',
'Die fantastische Welt von Oz <hr>Disney Spielfilm',
'Der Fuchs und das Mädchen ',
'Das Geheimnis der Mondprinzessin ',
'Das magische Buch von Arkandias ',
'Schneewittchen <hr>DEFA Farbfilm',
'Schneeweißchen und Rosenrot <hr>DEFA Farbfilm',
'Das tapfere Schneiderlein <hr>DEFA Farbfilm',
'Die Geschichte vom kleinen Muck <hr>DEFA Farbfilm',
'Spieglein Spieglein ',
'Der Hobbit [1] Eine unerwartete Reise ',
'Der Hobbit [2] Smaugs Einöde ',
'Der Hobbit [3] Die Schlacht der fünf Heere ',
'Herr der Ringe [1] Die Gefährten ',
'Herr der Ringe [2] Die zwei Türme ',
'Herr der Ringe [3] Die Rückkehr des Königs <hr>Disc 1',
'Phantastische Tierwesen und wo sie zu finden sind ',
'Grindelwalds Verbrechen ',
'Harry Potter [1] und der Stein der Weisen ',
'Harry Potter [2] und die Kammer des Schreckens ',
'Harry Potter [3] und der Gefangene von Askaban ',
'Harry Potter [4] und der Feuerkelch ',
'Harry Potter [5] und der Orden des Phönix ',
'Harry Potter [6] und der Halbblutprinz ',
'Harry Potter [7] und die Heiligtümer des Todes <hr>Teil 1',
'Harry Potter [7] und die Heiligtümer des Todes <hr>Teil 2',
'Flicka <hr>Teil 1 & Teil 2',
'Flicka <hr>Teil 3',
'Ruf der Pferde - Ein Mädchen folgt seinem Herzen ',
'Pferde-Collection <hr>3 Filme',
'Ostwind [1] Zusammen sind wir frei ',
'Ostwind [2] ',
'Ostwind [3] Aufbruch nach Ora ',
'Motiviere dein Pferd ',
'Black Beauty <hr>Disc 1',
'Black Beauty <hr>Disc 2',
'Für immer beste Freunde ',
'Elefant, Tiger & Co. - Alle suchen Elfriede <hr>DVD 1',
'Elefant, Tiger & Co. - Alle suchen Elfriede <hr>DVD 2',
'Spaniens letzte Luchse ',
'Wissen macht Ah! [2] Tierisch ekelig! ',
'Wissen macht Ah! [1] Bis der Arzt kommt! ',
'Wissen macht Ah! [3] Unbekannte Welten! ',
'Wissen macht Ah! <hr>Thema: Luft',
'Die erstaunliche Welt der Tiere <hr>DVD 1',
'Die erstaunliche Welt der Tiere <hr>DVD 2',
'Anna - Der Film ',
'Anna <hr>DVD 1',
'Anna <hr>DVD 2',
'Die Verlegerin ',
'Die Alleinseglerin ',
'Liebe geht durch alle Zeiten [1] Rubinrot ',
'Liebe geht durch alle Zeiten [2] Saphirblau ',
'Liebe geht durch alle Zeiten [3] Smaragdgrün ',
'Mara und der Feuerbringer ',
'Die unendliche Geschichte ',
'Das ist erst der Anfang! - Mission Ruhestand ',
'La Bohème <hr>Puccini / mit Anna Netrebko',
'Feet of Flames <hr>Michael Flatley',
'Lord of the Dance <hr>Michael Flatley',
'Wir können auch anders ',
'Der mit dem Wolf tanzt ',
'Jenseits von Afrika ',
'Die Ritter der Kokosnuss <hr>Monty Python',
'Das Leben des Brian <hr>Monty Python',
'Forrest Gump ',
'Auf der Suche nach dem goldenen Kind ',
'Honig im Kopf ',
'The Circle ',
'Sylvia - Eine Klasse für sich <hr>1/1-3',
'Sylvia - Eine Klasse für sich <hr>1/4-8',
'Sylvia - Eine Klasse für sich <hr>1/9-13',
'Sylvia - Eine Klasse für sich <hr>2/14-18',
'Sylvia - Eine Klasse für sich <hr>2/19-21',
'Sylvia - Eine Klasse für sich <hr>2/22-26',
'Der Ruf des Herzens - Verbranntes Land ',
'Helden aus der zweiten Reihe ',
'Speed ',
'The DaVinci Code ',
'The Huntsman & the Ice Queen ',
'Who&apos;s afraid of Virginia Woolf? ',
'Ich glaub&apos; mich knutscht ein Elch! ',
'Ghostbusters ',
'Und täglich grüßt das Murmeltier ',
'Der Vorname ',
'Madame Mallory und der Duft von Curry ',
'The King&apos;s Speech - Die Rede des Königs ',
'Amy und die Wildgänse ',
'Hidden Figures - Unbekannte Heldinnen ',
'Ballet Shoes <hr>Disc 1 - Film',
'Ballet Shoes <hr>Disc 2 - Bonus',
'Die Glücksritter <hr>"Trading Places"',
'Der Prinz aus Zamunda <hr>"Coming to America"',
'NVA <hr>Von der Sonnenallee in die Volksarmee',
'Ballon ',
'Amadeus <hr>Disc A - Spielfilm',
'Amadeus <hr>Disc B - Specials',
'Gundermann - 2 Filme aus 2 Gesellschaften <hr>Gundi Gundermann & Ende der Eisenzeit',
'Gundermann <hr>2018',
'Bohemian Rhapsody ',]
var film4 = [ 'Der Kaufmann von Venedig ',
'Luther <hr>Disc 1 - Hauptfilm',
'Luther <hr>Disc 2 - Bonus',
'Die Vermessung der Welt ',
'Geliebte Jane <hr>Jane Austen',
'Lost in Austen <hr>Disc 1 / Jane Austen',
'Lost in Austen <hr>Disc 2 / Jane Austen',
'Sinn und Sinnlichkeit <hr>Jane Austen',
'Betty und ihre Schwestern <hr>"Little Women"',
'Stolz und Vorurteil <hr>Jane Austen',
'Mansfield Park <hr>2009 / Jane Austen',
'Emma <hr>BBC / Disc 1 / Jane Austen',
'Emma <hr>BBC / Disc 2 / Jane Austen',
'Persuasion <hr>2007 / Jane Austen 21. Century Collection',
'Mansfield Park <hr>2007 / Jane Austen 21. Century Collection',
'Northanger Abbey <hr>2006 / Jane Austen 21. Century Collection',
'Love & Friendship <hr>Jane Austen',
'Sturmhöhe <hr>Disc 1 - Hauptfilm',
'Sturmhöhe <hr>Disc 2 - The Brontë Connection',
'The Tenant of Wildfell Hall <hr>Disc 1',
'The Tenant of Wildfell Hall <hr>Disc 2',
'Jane Eyre <hr>Disc 1',
'Jane Eyre <hr>Disc 2',
'Little Dorrit <hr>DVD 1',
'Little Dorrit <hr>DVD 2',
'Little Dorrit <hr>DVD 3',
'Little Dorrit <hr>DVD 4',
'I.Q. - Liebe ist relativ ',
'French Kiss ',
'Harry & Sally ',
'e-Mail für Dich ',
'Kate & Leopold ',
'Schlaflos in Seattle ',
'Reise ins Ich ',
'It&apos;s all about the women ',
'Die Akte <hr>J. Roberts / Seite A & Seite B / "The Pelican Brief"',
'Notting Hill ',
'Pretty Woman ',
'Die Braut, die sich nicht traut ',
'Erin Brockovich ',
'Mona Lisas Lächeln ',
'Die Hochzeit meines besten Freundes ',
'Verliebt in die Braut ',
'Traumfrauen ',
'Frühstück bei Tiffany ',
'Miss Undercover ',
'Was das Herz begehrt ',
'Während du schliefst... ',
'Das Haus am See ',
'Der Teufel trägt Prada ',
'Der Club der Teufelinnen <hr>"The First Wives Club"',
'Der Jane Austen Club ',
'Selbst ist die Braut ',
'Mr. & Mrs. Smith ',
'Forever my Girl ',
'Overboard ',
'Ruth & Alex ',
'Book Club ',
'Mother&apos;s Day ',
'Love happens ',
'Meine erfundene Frau ',
'Weil es dich gibt ',
'Wo die Liebe hinfällt ',
'Mamma mia! - Der Film ',
'When a Man loves a Woman ',
'In Sachen Liebe ',
'Mia and Me <hr>1/01',
'Mia and Me <hr>1/02',
'Mia and Me <hr>1/03',
'Mia and Me <hr>1/04',
'Mia and Me <hr>1/05',
'Mia and Me <hr>1/06',
'Mia and Me <hr>1/07',
'Mia and Me <hr>1/08',
'Mia and Me <hr>1/09',
'Mia and Me <hr>1/10',
'Mia and Me <hr>1/11',
'Mia and Me <hr>1/12',
'Mia and Me <hr>1/13',
'Mia and Me <hr>2/01',
'Mia and Me <hr>2/02',
'Mia and Me <hr>2/03',
'Mia and Me <hr>2/04',
'Mia and Me <hr>2/05',
'Mia and Me <hr>2/06',
'Mia and Me <hr>2/07',
'Mia and Me <hr>2/08',
'Mia and Me <hr>2/09',
'Mia and Me <hr>2/10',
'Mia and Me <hr>2/11',
'Mia and Me <hr>2/12',
'Mia and Me <hr>2/13',
'Mia and Me <hr>3/01',
'Mia and Me <hr>3/05',
'Mia and Me <hr>3/06',
'Mia and Me <hr>3/07',
'Mia and Me <hr>3/08',
'Pinguine aus Madagaskar <hr>King Julien Tag',
'Madagaskar 2 ',
'Yakari <hr>DVD 1',]
var film5 = [ 'Yakari <hr>DVD 2',
'Angelina Ballerina <hr>Teil 1',
'Angelina Ballerina <hr>Teil 2',
'Ric, der Rabe ',
'Das kleine Gespenst ',
'Landmaus & Stadtmaus auf Reisen ',
'Elefant, Tiger & Co. <hr>Friede nach Babyklau? / DVD 1',
'Elefant, Tiger & Co. <hr>Friede nach Babyklau? / DVD 2',
'Die Söhne der großen Bärin <hr>DEFA',
'Das Herz des Piraten & Der lange Ritt zur Schule ',
'Chingachgook, die große Schlange ',
'Spur der Steine ',
'Königskinder & Mit mir nicht, Madam! ',
'Leipzig im Herbst <hr>Geheime Aufnahmen der Montagsdemos',
'Das Ende des Politbüros <hr>Dokumentarfilm',
'Nikolai-Kirche <hr>Spielfilm-Drama',
'Pan Tau <hr>Staffel 1',
'Die Geschichte vom goldenen Taler ',
'Alfons Zitterbacke ',
'Ottokar, der Weltverbesserer ',
'Das Schulgespenst ',
'Moritz in der Litfaßsäule ',
'Die Reise nach Sundevit ',
'Der Prinz und der Abendstern ',
'Froschkönig ',
'König Drosselbart ',
'Sechse kommen um die Welt ',
'Fröhliches Madagaskar <hr>Weihnachtsfilm',
'Rudolph mit der roten Nase <hr>Weihnachtsfilm',
'Die Muppets Weihnachtsgeschichte <hr>Weihnachtsfilm',
'Santa Baby <hr>Weihnachtsfilm',
'Es ist ein Elch entsprungen <hr>Weihnachtsfilm',
'Die Feuerzangenbowle <hr>Weihnachtsfilm',
'Weihnachten in Familie [1] 1985-1995 <hr>Weihnachtsfilm',
'Weihnachten in Familie [2] 2000-2007 <hr>Weihnachtsfilm',
'Fröhliche Weihnachten, Mr. Bean <hr>Weihnachtsfilm',
'Tief durchatmen, die Familie kommt <hr>Weihnachtsfilm',
'Drei Haselnüsse für Aschenbrödel <hr>Weihnachtsfilm',
'Weihnachten mit Astrid Lindgren [2] <hr>Weihnachtsfilm / Neues aus Bullerbü & Ferien auf Saltkrokan',
'Pippi Langstrumpf geht von Bord <hr>Spielfilm mit Inger Nilsson',
'Der Naumburger Meister ',
'Das Vermächtnis [1] der Tempelritter ',
'Das Vermächtnis [2] des geheimen Buches ',
'Narnia [1] Der König von Narnia ',
'Narnia [2] Prinz Kaspian von Narnia ',
'Narnia [3] Die Reise auf der Morgenröte ',
'Laurel & Hardy - Verborgene Perlen ',
'Gregs Tagebuch [1] Von Idioten umzingelt ',
'Gregs Tagebuch [2] Gibt&apos;s Probleme? ',
'Gregs Tagebuch [3] Ich war&apos;s nicht! ',
'Ice Age <hr>DVD 1',
'Ice Age <hr>DVD 2 (Bonus)',
'Lauras Stern <hr>Disc 1 - Hauptfilm',
'Lauras Stern <hr>Disc 2 - Specials',
'Titanic <hr>Disc 1 - Teil 1',
'Titanic <hr>Disc 2 - Teil 2',
'Titanic <hr>Disc 3 - Bonus',
'Charlie Chaplin ',
'Zwerg Nase ',
'Das bucklige Pferdchen ',
'Die wilden Kerle 1 ',
'Die wilden Kerle 2 ',
'Werner - Das muss kesseln! ',
'Madagaskar ',
'Pippi Langstrumpf <hr>1 / TV-Episoden',
'Pippi Langstrumpf <hr>2 / TV-Episoden',
'Pippi Langstrumpf <hr>3 / TV-Episoden',
'Pippi Langstrumpf <hr>4 / TV-Episoden',
'Pippi Langstrumpf <hr>5 / TV-Episoden',
'Nils Holgersson <hr>Zeichentrick-Serie / Folgen 1-6',
'Unser Sandmännchen - Traumsand in Gefahr <hr>mit Plumps und Pittiplatsch',
'Unser Sandmännchen - La, le, lu <hr>mit Plumps und Pittiplatsch',
'Sendung mit der Maus - Gute-Nacht-Geschichten ',
'Adolars phantastische Abendteuer ',
'Hilfe, ich habe meine Lehrerin geschrumpft ',
'Willkommen bei den Hartmanns ',
'Love&apos;s Kitchen - Ein Dessert zum Verlieben ',
'Mr. Bean - Der Gruselfilm ',
'Mr. Bean <hr>1/01',
'Mr. Bean <hr>1/02',
'Mr. Bean <hr>1/03',
'Mr. Bean <hr>1/04',
'Mr. Bean <hr>1/05',
'Mr. Bean <hr>1/06',
'Pinguine aus Madagaskar <hr>Operation: Impossible Possible',
'Pinguine aus Madagaskar <hr>Das Geheimnis der Weihnacht',
'Pinguine aus Madagaskar <hr>Operation: Ferienspaß',
'Pinguine aus Madagaskar <hr>Geheimauftrag: Pinguine',
'Pinguine aus Madagaskar <hr>Spezialeinheit: Pinguin',
'Pinguine aus Madagaskar - Der Film ',
'Timm Thaler oder Das verkaufte Lachen ',
'Mia and Me <hr>3/02',
'Mia and Me <hr>3/03',
'Mia and Me <hr>3/04',
'Das fliegende Klassenzimmer ',
'Frau Müller muss weg! ',
'Florence Foster Jenkins ',
'Little Amadeus <hr>1',
'Little Amadeus <hr>2',
'Little Amadeus <hr>3',]
var film6 = [ 'Little Amadeus <hr>4',
'Little Amadeus <hr>5',
'Little Amadeus <hr>6',
'Little Amadeus <hr>7',
'Little Amadeus <hr>8',
'Pettersson und Findus ',
'Lotte im Dorf der Erfinder ',
'Pittiplatsch im Koboldland <hr>Teil 2 / DVD 1',
'Pittiplatsch im Koboldland <hr>Teil 2 / DVD 2',
'Charlie und die Schokoladenfabrik ',
'Herr der Diebe ',
'Arthur, der Engel ',
'Unser Sandmännchen - Tierbabys ',
'Prinzessin Lillifee ',
'Mullewapp ',
'Bibi Blocksberg <hr>DVD 1',
'Bibi Blocksberg <hr>DVD 2',
'Desperate Housewives <hr>1/01-04',
'Desperate Housewives <hr>1/05-08',
'Desperate Housewives <hr>1/09-12',
'Desperate Housewives <hr>1/13-16',
'Desperate Housewives <hr>1/17-20',
'Desperate Housewives <hr>1/21-23',
'Marvi Hämmer <hr>1/01',
'Marvi Hämmer <hr>1/02',
'Marvi Hämmer <hr>1/03',
'Marvi Hämmer <hr>1/04 Bonus-DVD',
'Marvi Hämmer <hr>2/01',
'Marvi Hämmer <hr>2/02',
'Marvi Hämmer <hr>2/03',
'Marvi Hämmer <hr>2/04',
'Nachts im Museum <hr>Das geheimnisvolle Grabmal',
'Jagdfieber 1 ',
'Jagdfieber 2 ',
'Jagdfieber 3 ',
'Willi will&apos;s wissen <hr>Abenteuer & Dunkle Höhlen',
'Willi will&apos;s wissen <hr>Fischer & Krabbenkutter',
'Willi will&apos;s wissen <hr>Fähre & Hafen Hamburg',
'Spion in Spitzenhöschen <hr>Doris Day',
'Was diese Frau so alles treibt <hr>Doris Day (Happy-Seife)',
'Snowden ',
'Petterson <hr>selbst gebrannt',
'Lilalu - Abenteuer im Schepperland <hr>1',
'Lilalu - Abenteuer im Schepperland <hr>2',
'Lilalu - Abenteuer im Schepperland <hr>3',
'Lilalu - Abenteuer im Schepperland <hr>4',
'Lilalu - Abenteuer im Schepperland <hr>5',
'Lilalu - Abenteuer im Schepperland <hr>6',
'Percy Jackson - Diebe im Olymp ',
'Die Weihnachtsgans Auguste <hr>DEFA-Farbfilm',
'Die Zauberflöte für Kinder <hr>Oper Zürich',
'Familie Feuerstein <hr>3/1',
'Familie Feuerstein <hr>3/2',
'Familie Feuerstein <hr>3/3',
'Familie Feuerstein <hr>3/4',
'Familie Feuerstein <hr>3/5',]



   
      
       
     

    let zahl1;
    zahl1 = Math.floor( Math.random() * 556 + 0 )
        
        
        
     zahl1 < 100  ?  document.write(film1[zahl1])  :  zahl1 < 200  ?  document.write(film2[zahl1 --- 100])
                                                   :  zahl1 < 300  ?  document.write(film3[zahl1 --- 200])
                                                   :  zahl1 < 400  ?  document.write(film4[zahl1 --- 300])
                                                   :  zahl1 < 500  ?  document.write(film5[zahl1 --- 400])
                                                   :  document.write(film6[zahl1 --- 500])






  //      document.write("Hallo <hr> Hannes")
