var d  = new Date();
var tt = d.getDate();
var m =  d.getMonth();
var yy = d.getFullYear();
var mm	= ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember']
// document.writeln(tt +". "+ mm[m] +" "+ yy)


var mon = d.getMonth() + 1
var dz = d.getDate() + "" + mon
//--------------------------------------


dz == 11 ? document.writeln("<a href='#1'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 21 ? document.writeln("<a href='#1'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 31 ? document.writeln("<a href='#1'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 41 ? document.writeln("<a href='#1'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 51 ? document.writeln("<a href='#1'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 61 ? document.writeln("<a href='#1'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 71 ? document.writeln("<a href='#1'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 81 ? document.writeln("<a href='#2'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 91 ? document.writeln("<a href='#2'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 101 ? document.writeln("<a href='#2'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 111 ? document.writeln("<a href='#2'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 121 ? document.writeln("<a href='#2'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 131 ? document.writeln("<a href='#2'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 141 ? document.writeln("<a href='#2'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 151 ? document.writeln("<a href='#3'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 161 ? document.writeln("<a href='#3'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 171 ? document.writeln("<a href='#3'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 181 ? document.writeln("<a href='#3'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 191 ? document.writeln("<a href='#3'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 201 ? document.writeln("<a href='#3'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 211 ? document.writeln("<a href='#3'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 221 ? document.writeln("<a href='#4'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 231 ? document.writeln("<a href='#4'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 241 ? document.writeln("<a href='#4'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 251 ? document.writeln("<a href='#4'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 261 ? document.writeln("<a href='#4'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 271 ? document.writeln("<a href='#4'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 281 ? document.writeln("<a href='#4'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 291 ? document.writeln("<a href='#5'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 301 ? document.writeln("<a href='#5'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 311 ? document.writeln("<a href='#5'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 12 ? document.writeln("<a href='#5'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 22 ? document.writeln("<a href='#5'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 32 ? document.writeln("<a href='#5'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 42 ? document.writeln("<a href='#5'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 52 ? document.writeln("<a href='#6'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 62 ? document.writeln("<a href='#6'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 72 ? document.writeln("<a href='#6'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 82 ? document.writeln("<a href='#6'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 92 ? document.writeln("<a href='#6'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 102 ? document.writeln("<a href='#6'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 112 ? document.writeln("<a href='#6'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 122 ? document.writeln("<a href='#7'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 132 ? document.writeln("<a href='#7'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 142 ? document.writeln("<a href='#7'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 152 ? document.writeln("<a href='#7'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 162 ? document.writeln("<a href='#7'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 172 ? document.writeln("<a href='#7'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 182 ? document.writeln("<a href='#7'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 192 ? document.writeln("<a href='#8'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 202 ? document.writeln("<a href='#8'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 212 ? document.writeln("<a href='#8'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 222 ? document.writeln("<a href='#8'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 232 ? document.writeln("<a href='#8'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 242 ? document.writeln("<a href='#8'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 252 ? document.writeln("<a href='#8'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 262 ? document.writeln("<a href='#9'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 272 ? document.writeln("<a href='#9'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 282 ? document.writeln("<a href='#9'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 13 ? document.writeln("<a href='#9'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 23 ? document.writeln("<a href='#9'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 33 ? document.writeln("<a href='#9'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 43 ? document.writeln("<a href='#9'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 53 ? document.writeln("<a href='#10'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 63 ? document.writeln("<a href='#10'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 73 ? document.writeln("<a href='#10'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 83 ? document.writeln("<a href='#10'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 93 ? document.writeln("<a href='#10'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 103 ? document.writeln("<a href='#10'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 113 ? document.writeln("<a href='#10'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 123 ? document.writeln("<a href='#11'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 133 ? document.writeln("<a href='#11'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 143 ? document.writeln("<a href='#11'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 153 ? document.writeln("<a href='#11'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 163 ? document.writeln("<a href='#11'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 173 ? document.writeln("<a href='#11'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 183 ? document.writeln("<a href='#11'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 193 ? document.writeln("<a href='#12'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 203 ? document.writeln("<a href='#12'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 213 ? document.writeln("<a href='#12'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 223 ? document.writeln("<a href='#12'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 233 ? document.writeln("<a href='#12'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 243 ? document.writeln("<a href='#12'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 253 ? document.writeln("<a href='#12'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 263 ? document.writeln("<a href='#13'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 273 ? document.writeln("<a href='#13'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 283 ? document.writeln("<a href='#13'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 293 ? document.writeln("<a href='#13'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 303 ? document.writeln("<a href='#13'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 313 ? document.writeln("<a href='#13'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 14 ? document.writeln("<a href='#13'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 24 ? document.writeln("<a href='#14'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 34 ? document.writeln("<a href='#14'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 44 ? document.writeln("<a href='#14'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 54 ? document.writeln("<a href='#14'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 64 ? document.writeln("<a href='#14'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 74 ? document.writeln("<a href='#14'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 84 ? document.writeln("<a href='#14'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 94 ? document.writeln("<a href='#15'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 104 ? document.writeln("<a href='#15'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 114 ? document.writeln("<a href='#15'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 124 ? document.writeln("<a href='#15'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 134 ? document.writeln("<a href='#15'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 144 ? document.writeln("<a href='#15'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 154 ? document.writeln("<a href='#15'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 164 ? document.writeln("<a href='#16'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 174 ? document.writeln("<a href='#16'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 184 ? document.writeln("<a href='#16'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 194 ? document.writeln("<a href='#16'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 204 ? document.writeln("<a href='#16'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 214 ? document.writeln("<a href='#16'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 224 ? document.writeln("<a href='#16'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 234 ? document.writeln("<a href='#17'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 244 ? document.writeln("<a href='#17'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 254 ? document.writeln("<a href='#17'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 264 ? document.writeln("<a href='#17'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 274 ? document.writeln("<a href='#17'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 284 ? document.writeln("<a href='#17'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 294 ? document.writeln("<a href='#17'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 304 ? document.writeln("<a href='#18'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 15 ? document.writeln("<a href='#18'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 25 ? document.writeln("<a href='#18'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 35 ? document.writeln("<a href='#18'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 45 ? document.writeln("<a href='#18'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 55 ? document.writeln("<a href='#18'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 65 ? document.writeln("<a href='#18'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 75 ? document.writeln("<a href='#19'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 85 ? document.writeln("<a href='#19'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 95 ? document.writeln("<a href='#19'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 105 ? document.writeln("<a href='#19'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 115 ? document.writeln("<a href='#19'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 125 ? document.writeln("<a href='#19'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 135 ? document.writeln("<a href='#19'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 145 ? document.writeln("<a href='#20'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 155 ? document.writeln("<a href='#20'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 165 ? document.writeln("<a href='#20'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 175 ? document.writeln("<a href='#20'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 185 ? document.writeln("<a href='#20'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 195 ? document.writeln("<a href='#20'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 205 ? document.writeln("<a href='#20'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 215 ? document.writeln("<a href='#21'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 225 ? document.writeln("<a href='#21'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 235 ? document.writeln("<a href='#21'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 245 ? document.writeln("<a href='#21'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 255 ? document.writeln("<a href='#21'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 265 ? document.writeln("<a href='#21'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 275 ? document.writeln("<a href='#21'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 285 ? document.writeln("<a href='#22'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 295 ? document.writeln("<a href='#22'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 305 ? document.writeln("<a href='#22'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 315 ? document.writeln("<a href='#22'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 16 ? document.writeln("<a href='#22'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 26 ? document.writeln("<a href='#22'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 36 ? document.writeln("<a href='#22'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 46 ? document.writeln("<a href='#23'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 56 ? document.writeln("<a href='#23'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 66 ? document.writeln("<a href='#23'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 76 ? document.writeln("<a href='#23'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 86 ? document.writeln("<a href='#23'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 96 ? document.writeln("<a href='#23'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 106 ? document.writeln("<a href='#23'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 116 ? document.writeln("<a href='#24'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 126 ? document.writeln("<a href='#24'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 136 ? document.writeln("<a href='#24'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 146 ? document.writeln("<a href='#24'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 156 ? document.writeln("<a href='#24'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 166 ? document.writeln("<a href='#24'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 176 ? document.writeln("<a href='#24'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 186 ? document.writeln("<a href='#25'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 196 ? document.writeln("<a href='#25'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 206 ? document.writeln("<a href='#25'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 216 ? document.writeln("<a href='#25'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 226 ? document.writeln("<a href='#25'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 236 ? document.writeln("<a href='#25'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 246 ? document.writeln("<a href='#25'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 256 ? document.writeln("<a href='#26'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 266 ? document.writeln("<a href='#26'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 276 ? document.writeln("<a href='#26'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 286 ? document.writeln("<a href='#26'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 296 ? document.writeln("<a href='#26'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 306 ? document.writeln("<a href='#26'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 17 ? document.writeln("<a href='#26'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 27 ? document.writeln("<a href='#27'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 37 ? document.writeln("<a href='#27'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 47 ? document.writeln("<a href='#27'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 57 ? document.writeln("<a href='#27'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 67 ? document.writeln("<a href='#27'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 77 ? document.writeln("<a href='#27'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 87 ? document.writeln("<a href='#27'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 97 ? document.writeln("<a href='#28'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 107 ? document.writeln("<a href='#28'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 117 ? document.writeln("<a href='#28'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 127 ? document.writeln("<a href='#28'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 137 ? document.writeln("<a href='#28'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 147 ? document.writeln("<a href='#28'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 157 ? document.writeln("<a href='#28'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 167 ? document.writeln("<a href='#29'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 177 ? document.writeln("<a href='#29'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 187 ? document.writeln("<a href='#29'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 197 ? document.writeln("<a href='#29'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 207 ? document.writeln("<a href='#29'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 217 ? document.writeln("<a href='#29'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 227 ? document.writeln("<a href='#29'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 237 ? document.writeln("<a href='#30'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 247 ? document.writeln("<a href='#30'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 257 ? document.writeln("<a href='#30'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 267 ? document.writeln("<a href='#30'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 277 ? document.writeln("<a href='#30'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 287 ? document.writeln("<a href='#30'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 297 ? document.writeln("<a href='#30'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 307 ? document.writeln("<a href='#31'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 317 ? document.writeln("<a href='#31'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 18 ? document.writeln("<a href='#31'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 28 ? document.writeln("<a href='#31'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 38 ? document.writeln("<a href='#31'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 48 ? document.writeln("<a href='#31'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 58 ? document.writeln("<a href='#31'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 68 ? document.writeln("<a href='#32'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 78 ? document.writeln("<a href='#32'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 88 ? document.writeln("<a href='#32'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 98 ? document.writeln("<a href='#32'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 108 ? document.writeln("<a href='#32'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 118 ? document.writeln("<a href='#32'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 128 ? document.writeln("<a href='#32'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 138 ? document.writeln("<a href='#33'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 148 ? document.writeln("<a href='#33'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 158 ? document.writeln("<a href='#33'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 168 ? document.writeln("<a href='#33'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 178 ? document.writeln("<a href='#33'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 188 ? document.writeln("<a href='#33'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 198 ? document.writeln("<a href='#33'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 208 ? document.writeln("<a href='#34'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 218 ? document.writeln("<a href='#34'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 228 ? document.writeln("<a href='#34'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 238 ? document.writeln("<a href='#34'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 248 ? document.writeln("<a href='#34'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 258 ? document.writeln("<a href='#34'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 268 ? document.writeln("<a href='#34'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 278 ? document.writeln("<a href='#35'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 288 ? document.writeln("<a href='#35'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 298 ? document.writeln("<a href='#35'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 308 ? document.writeln("<a href='#35'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 318 ? document.writeln("<a href='#35'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 19 ? document.writeln("<a href='#35'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 29 ? document.writeln("<a href='#35'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 39 ? document.writeln("<a href='#36'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 49 ? document.writeln("<a href='#36'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 59 ? document.writeln("<a href='#36'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 69 ? document.writeln("<a href='#36'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 79 ? document.writeln("<a href='#36'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 89 ? document.writeln("<a href='#36'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 99 ? document.writeln("<a href='#36'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 109 ? document.writeln("<a href='#37'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 119 ? document.writeln("<a href='#37'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 129 ? document.writeln("<a href='#37'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 139 ? document.writeln("<a href='#37'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 149 ? document.writeln("<a href='#37'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 159 ? document.writeln("<a href='#37'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 169 ? document.writeln("<a href='#37'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 179 ? document.writeln("<a href='#38'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 189 ? document.writeln("<a href='#38'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 199 ? document.writeln("<a href='#38'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 209 ? document.writeln("<a href='#38'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 219 ? document.writeln("<a href='#38'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 229 ? document.writeln("<a href='#38'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 239 ? document.writeln("<a href='#38'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 249 ? document.writeln("<a href='#39'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 259 ? document.writeln("<a href='#39'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 269 ? document.writeln("<a href='#39'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 279 ? document.writeln("<a href='#39'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 289 ? document.writeln("<a href='#39'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 299 ? document.writeln("<a href='#39'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 309 ? document.writeln("<a href='#39'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 110 ? document.writeln("<a href='#40'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 210 ? document.writeln("<a href='#40'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 310 ? document.writeln("<a href='#40'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 410 ? document.writeln("<a href='#40'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 510 ? document.writeln("<a href='#40'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 610 ? document.writeln("<a href='#40'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 710 ? document.writeln("<a href='#40'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 810 ? document.writeln("<a href='#41'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 910 ? document.writeln("<a href='#41'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1010 ? document.writeln("<a href='#41'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1110 ? document.writeln("<a href='#41'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1210 ? document.writeln("<a href='#41'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1310 ? document.writeln("<a href='#41'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1410 ? document.writeln("<a href='#41'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1510 ? document.writeln("<a href='#42'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1610 ? document.writeln("<a href='#42'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1710 ? document.writeln("<a href='#42'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1810 ? document.writeln("<a href='#42'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1910 ? document.writeln("<a href='#42'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2010 ? document.writeln("<a href='#42'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2110 ? document.writeln("<a href='#42'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2210 ? document.writeln("<a href='#43'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2310 ? document.writeln("<a href='#43'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2410 ? document.writeln("<a href='#43'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2510 ? document.writeln("<a href='#43'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2610 ? document.writeln("<a href='#43'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2710 ? document.writeln("<a href='#43'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2810 ? document.writeln("<a href='#43'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2910 ? document.writeln("<a href='#44'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 3010 ? document.writeln("<a href='#44'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 3110 ? document.writeln("<a href='#44'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 111 ? document.writeln("<a href='#44'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 211 ? document.writeln("<a href='#44'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 311 ? document.writeln("<a href='#44'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 411 ? document.writeln("<a href='#44'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 511 ? document.writeln("<a href='#45'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 611 ? document.writeln("<a href='#45'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 711 ? document.writeln("<a href='#45'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 811 ? document.writeln("<a href='#45'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 911 ? document.writeln("<a href='#45'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1011 ? document.writeln("<a href='#45'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1111 ? document.writeln("<a href='#45'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1211 ? document.writeln("<a href='#46'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1311 ? document.writeln("<a href='#46'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1411 ? document.writeln("<a href='#46'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1511 ? document.writeln("<a href='#46'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1611 ? document.writeln("<a href='#46'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1711 ? document.writeln("<a href='#46'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1811 ? document.writeln("<a href='#46'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1911 ? document.writeln("<a href='#47'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2011 ? document.writeln("<a href='#47'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2111 ? document.writeln("<a href='#47'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2211 ? document.writeln("<a href='#47'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2311 ? document.writeln("<a href='#47'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2411 ? document.writeln("<a href='#47'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2511 ? document.writeln("<a href='#47'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2611 ? document.writeln("<a href='#48'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2711 ? document.writeln("<a href='#48'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2811 ? document.writeln("<a href='#48'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2911 ? document.writeln("<a href='#48'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 3011 ? document.writeln("<a href='#48'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 112 ? document.writeln("<a href='#48'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 212 ? document.writeln("<a href='#48'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 312 ? document.writeln("<a href='#49'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 412 ? document.writeln("<a href='#49'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 512 ? document.writeln("<a href='#49'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 612 ? document.writeln("<a href='#49'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 712 ? document.writeln("<a href='#49'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 812 ? document.writeln("<a href='#49'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 912 ? document.writeln("<a href='#49'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1012 ? document.writeln("<a href='#50'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1112 ? document.writeln("<a href='#50'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1212 ? document.writeln("<a href='#50'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1312 ? document.writeln("<a href='#50'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1412 ? document.writeln("<a href='#50'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1512 ? document.writeln("<a href='#50'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1612 ? document.writeln("<a href='#50'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1712 ? document.writeln("<a href='#51'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1812 ? document.writeln("<a href='#51'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 1912 ? document.writeln("<a href='#51'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2012 ? document.writeln("<a href='#51'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2112 ? document.writeln("<a href='#51'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2212 ? document.writeln("<a href='#51'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2312 ? document.writeln("<a href='#51'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2412 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2512 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2612 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2712 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2812 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 2912 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 3012 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
dz == 3112 ? document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>") :
document.writeln("<a href='#52'><button style='font-size:inherit;'>Aktuelle Woche</button></a>")